import type { Metadata } from "next"
import { 
  Karla as WindowGrabFont,
  Urbanist as HeroFont,
  Outfit as HeaderFont,
  Comfortaa as BodyFont,
  M_PLUS_1p as TinyFont,
} from "next/font/google"
import "./globals.css"

import { MetaTags } from "@/app/MetaTags"

import { ToolTipProvider } from "@/components/ToolTip"

import { InitialLoad } from "@/os/InitialLoad"
import { StorageProvider } from "@/os/storage"
import { SystemProvider } from "@/os/system"
import { WindowsProvider } from "@/os/windows"
import { ControllerProvider } from "@/os/controller"

const windowGrabFont = WindowGrabFont({
  subsets: ["latin"],
  weight: "300",
  style: "normal",
  variable: "--font-window-grab",
})

const heroFont = HeroFont({
  subsets: ["latin"],
  weight: "900",
  style: "normal",
  variable: "--font-hero",
})

const headerFont = HeaderFont({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  style: "normal",
  variable: "--font-header",
})

const bodyFont = BodyFont({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  style: "normal",
  variable: "--font-body",
})

const tinyFont = TinyFont({
  subsets: ["latin"],
  weight: ["300", "400"],
  style: "normal",
  variable: "--font-tiny",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <MetaTags />
      </head>
      <body className={`${bodyFont.className} ${windowGrabFont.variable} ${heroFont.variable} ${headerFont.variable} ${bodyFont.variable} ${tinyFont.variable}`}>
        <StorageProvider>
          <InitialLoad />
          <SystemProvider>
            <ToolTipProvider>
              <WindowsProvider>
                <ControllerProvider>
                  <div id="screen" className="h-full w-full bg-repeat bg-pattern-light dark:bg-pattern-dark">
                    <div className="flex safe-h-full flex-col items-center justify-between p-24">
                      {children}
                    </div>
                  </div>
                </ControllerProvider>
              </WindowsProvider>
            </ToolTipProvider>
          </SystemProvider>
        </StorageProvider>
      </body>
    </html>
  )
}
