import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

import { MetaTags } from "./components/MetaTags"
import { ToolTipProvider } from "@/hooks/useToolTip"
import { ControlBarProvider } from "@/hooks/useControlBar"
import { InitialLoad } from "@/app/utils/InitialLoad"

const inter = Inter({ subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <MetaTags />
      </head>
      <body className={inter.className}>
        <InitialLoad />
        <ToolTipProvider>
          <ControlBarProvider>
            <div id="screen" className="h-full w-full bg-repeat bg-pattern-light dark:bg-pattern-dark opacity-50">
              <div className="flex safe-h-full flex-col items-center justify-between p-24">
                {children}
              </div>
            </div>
          </ControlBarProvider>
        </ToolTipProvider>
      </body>
    </html>
  )
}
